title: <p align="center"> Aditya Repekar </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="docs/Aditya_Kiran_Repekar.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/repekaraditya">LinkedIn</a> |
  <a href="https://github.com/adityarepekar">GitHub</a>
  
  <br>   
  
I am a result-driven Machine Learning Engineer with a passion for building high-quality Machine Learning Systems. With over 5 years of experience in the industry, I have developed a strong expertise in MLOps, DevOps and Cloud, helping companies build, deploy and monitor applications and machine learning models at scale.

My technical skills include proficiency in popular programming languages such as Python and SQL, as well as experience working with frameworks like TensorFlow and Scikit-learn. I have experience in designing and implementing scalable CI/CD pipelines, building robust monitoring and alerting systems.

Throughout my career, I have demonstrated a strong ability to work effectively in cross-functional teams, collaborating with data scientists, machine learning engineers, and other stakeholders to deliver high-quality machine learning systems on time and within budget. I am a strong communicator and is committed to delivering excellent customer service.

In my free time, I enjoy keeping up with the latest developments in the MLOps field, experimenting with new tools and techniques. I am passionate about using my skills to help companies leverage the power of machine learning and artificial intelligence to drive innovation and growth.
  <br>
  </p>



theme: jekyll-theme-minimal
